/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear auth cookies.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Get the current authenticated user's profile.
         */
        get: operations["get_current_user_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Profile
         * @description Update the current user's profile.
         */
        patch: operations["update_profile_v1_users_me_patch"];
        trace?: never;
    };
    "/v1/profile/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Photos
         * @description Get all photos for the current user.
         */
        get: operations["list_photos_v1_profile_photos_get"];
        put?: never;
        /**
         * Add Photo
         * @description Add a new photo to the user's profile.
         */
        post: operations["add_photo_v1_profile_photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Photo
         * @description Delete a photo from the user's profile.
         */
        delete: operations["remove_photo_v1_profile_photos__photo_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile/photos/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reorder User Photos
         * @description Reorder photos by providing photo IDs in desired order.
         */
        put: operations["reorder_user_photos_v1_profile_photos_reorder_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile/prompts/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Available Prompts
         * @description Get list of available prompt questions.
         */
        get: operations["list_available_prompts_v1_profile_prompts_available_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Prompts
         * @description Get all prompts for the current user.
         */
        get: operations["list_prompts_v1_profile_prompts_get"];
        put?: never;
        /**
         * Add Prompt
         * @description Add a new prompt answer to the user's profile.
         */
        post: operations["add_prompt_v1_profile_prompts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile/prompts/{prompt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Prompt
         * @description Delete a prompt from the user's profile.
         */
        delete: operations["remove_prompt_v1_profile_prompts__prompt_id__delete"];
        options?: never;
        head?: never;
        /**
         * Edit Prompt
         * @description Update an existing prompt answer.
         */
        patch: operations["edit_prompt_v1_profile_prompts__prompt_id__patch"];
        trace?: never;
    };
    "/v1/profile/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quiz Responses
         * @description Get the current user's quiz responses.
         */
        get: operations["get_quiz_responses_v1_profile_quiz_get"];
        put?: never;
        /**
         * Submit Quiz Answers
         * @description Submit quiz answers and receive generated badges.
         */
        post: operations["submit_quiz_answers_v1_profile_quiz_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile/badges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Badges
         * @description Get all badges for the current user.
         */
        get: operations["list_badges_v1_profile_badges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile/completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile Completion
         * @description Get profile completion status and percentage.
         */
        get: operations["get_profile_completion_v1_profile_completion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Discovery Feed
         * @description Get discovery feed with up to 10 curated profiles.
         *
         *     Returns profiles ranked by compatibility, completeness, and activity.
         *     Handles scarcity gracefully with suggestions if pool is limited.
         */
        get: operations["get_discovery_feed_v1_matching_discover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Like To User
         * @description Send a like to another user.
         *
         *     - Limited to 10 likes per day
         *     - First 5 likes require a comment
         *     - Rate limited to prevent spam
         *     - Creates a match if mutual
         */
        post: operations["send_like_to_user_v1_matching_likes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/likes/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Likes Received
         * @description Get likes received that you haven't acted on yet.
         */
        get: operations["get_likes_received_v1_matching_likes_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/passes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pass On User
         * @description Pass on a profile.
         *
         *     - Not permanent: expires after 30 days
         *     - User will see this profile again after cooldown
         */
        post: operations["pass_on_user_v1_matching_passes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/passes/{to_user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Undo Pass On User
         * @description Undo a pass (limited usage).
         *
         *     Use this if you accidentally passed on someone.
         */
        delete: operations["undo_pass_on_user_v1_matching_passes__to_user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Matches
         * @description Get all your matches.
         */
        get: operations["list_matches_v1_matching_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unmatch User
         * @description Unmatch from a match.
         */
        delete: operations["unmatch_user_v1_matching_matches__match_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Block Another User
         * @description Block a user.
         *
         *     - They will never appear in your feed again
         *     - You will never appear in their feed
         *     - Any active match will be ended
         */
        post: operations["block_another_user_v1_matching_blocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Another User
         * @description Report a user for review.
         *
         *     - User will be automatically blocked
         *     - Report will be reviewed by moderators
         */
        post: operations["report_another_user_v1_matching_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matching/compatibility/{other_user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Compatibility
         * @description Get compatibility details with another user.
         */
        get: operations["get_compatibility_v1_matching_compatibility__other_user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daily-discovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Daily Discovery
         * @description Get current daily discovery state and profile to view.
         *
         *     Returns:
         *     - Today's discovery state (profiles, progress, free pick status)
         *     - Current profile to view (if not complete)
         *     - Active view info if already viewing a profile
         */
        get: operations["get_daily_discovery_v1_daily_discovery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daily-discovery/view/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start View
         * @description Start viewing a profile. Records server-side timestamp.
         *
         *     Call this when displaying a profile to the user.
         *     The server records the exact start time for validation.
         */
        post: operations["start_view_v1_daily_discovery_view_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daily-discovery/view/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End View
         * @description End viewing a profile with an action (interest or pass).
         *
         *     Server validates:
         *     - View exists and belongs to user
         *     - For 'interest' with free_pick already used: minimum view time met
         *     - Server calculates actual duration (not client-provided)
         *
         *     Free pick rules:
         *     - First interest of the day is always allowed (becomes 'free_pick')
         *     - Subsequent interests require MINIMUM_VIEW_SECONDS seconds of viewing
         */
        post: operations["end_view_v1_daily_discovery_view_end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daily-discovery/interest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Express Interest
         * @description Express interest in a profile (convenience endpoint).
         *
         *     Ends the view with 'interest' action and returns next profile.
         */
        post: operations["express_interest_v1_daily_discovery_interest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daily-discovery/pass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pass Profile
         * @description Pass on a profile (convenience endpoint).
         *
         *     Ends the view with 'pass' action and returns next profile.
         *     Pass does not require minimum view time.
         */
        post: operations["pass_profile_v1_daily_discovery_pass_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/daily-discovery/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset For Testing
         * @description Reset daily discovery state for testing.
         *
         *     Only available in development mode.
         */
        post: operations["reset_for_testing_v1_daily_discovery_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/matches/{match_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Messages
         * @description Get message history for a match.
         */
        get: operations["get_messages_v1_chat_matches__match_id__messages_get"];
        put?: never;
        /**
         * Send Message
         * @description Send a message (REST fallback, prefer WebSocket).
         */
        post: operations["send_message_v1_chat_matches__match_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/matches/{match_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Read
         * @description Mark all messages in a match as read.
         */
        post: operations["mark_read_v1_chat_matches__match_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/matches/{match_id}/unread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Unread Count
         * @description Get unread message count for a match.
         */
        get: operations["get_unread_count_v1_chat_matches__match_id__unread_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Message
         * @description Delete a message (soft delete, sender only).
         */
        delete: operations["delete_message_v1_chat_messages__message_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AvailablePromptsResponse */
        AvailablePromptsResponse: {
            /** Prompts */
            prompts: string[];
        };
        /** BadgeResponse */
        BadgeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Badge Type */
            badge_type: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BlockCreate */
        BlockCreate: {
            /**
             * Blocked Id
             * Format: uuid
             */
            blocked_id: string;
        };
        /** BlockOut */
        BlockOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Blocked Id
             * Format: uuid
             */
            blocked_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CompatibilityOut */
        CompatibilityOut: {
            /** Overall Score */
            overall_score: number;
            /** Trait Comparisons */
            trait_comparisons: components["schemas"]["TraitComparisonOut"][];
            /** Summary */
            summary: string;
            /** Highlights */
            highlights: string[];
        };
        /**
         * DailyDiscoveryInitResponse
         * @description Response when initializing/getting daily discovery.
         */
        DailyDiscoveryInitResponse: {
            state: components["schemas"]["DailyDiscoveryStateOut"];
            current_profile: components["schemas"]["DailyDiscoveryProfileOut"] | null;
            /** Active View Id */
            active_view_id?: string | null;
            /** Active View Started At */
            active_view_started_at?: string | null;
        };
        /**
         * DailyDiscoveryProfileOut
         * @description Profile for daily discovery - age calculated server-side, no PII.
         */
        DailyDiscoveryProfileOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            /** Age */
            age: number | null;
            /** Bio */
            bio: string | null;
            /** Location */
            location: string | null;
            /** Photos */
            photos: components["schemas"]["DiscoveryPhotoOut"][];
            /** Prompts */
            prompts: components["schemas"]["DiscoveryPromptOut"][];
            /** Badges */
            badges: components["schemas"]["DiscoveryBadgeOut"][];
        };
        /**
         * DailyDiscoveryStateOut
         * @description Current state of user's daily discovery.
         */
        DailyDiscoveryStateOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Profiles */
            profiles: components["schemas"]["DailyDiscoveryProfileOut"][];
            /** Current Index */
            current_index: number;
            /** Total Profiles */
            total_profiles: number;
            /** Viewed Count */
            viewed_count: number;
            /** Is Free Pick */
            is_free_pick: boolean;
            /** Free Pick Used */
            free_pick_used: boolean;
            /** Interested Count */
            interested_count: number;
            /** Passed Count */
            passed_count: number;
            /** Is Complete */
            is_complete: boolean;
        };
        /** DiscoveryBadgeOut */
        DiscoveryBadgeOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
        };
        /** DiscoveryPhotoOut */
        DiscoveryPhotoOut: {
            /** Id */
            id: string;
            /** Url */
            url: string;
            /** Order */
            order: number;
        };
        /** DiscoveryProfileOut */
        DiscoveryProfileOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            /** Age */
            age: number | null;
            /** Gender */
            gender: string | null;
            /** Bio */
            bio: string | null;
            /** Location */
            location: string | null;
            /** Photos */
            photos: {
                [key: string]: unknown;
            }[];
            /** Prompts */
            prompts: {
                [key: string]: unknown;
            }[];
            compatibility: components["schemas"]["CompatibilityOut"] | null;
            /** Is New User */
            is_new_user: boolean;
        };
        /** DiscoveryPromptOut */
        DiscoveryPromptOut: {
            /** Id */
            id: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
        };
        /** DiscoveryResultOut */
        DiscoveryResultOut: {
            /** Profiles */
            profiles: components["schemas"]["DiscoveryProfileOut"][];
            /** Total Available */
            total_available: number;
            /** Exhausted Pool */
            exhausted_pool: boolean;
            /** Suggestions */
            suggestions: string[];
            /** Likes Remaining */
            likes_remaining: number;
        };
        /**
         * ExpressInterestRequest
         * @description Request to express interest in a profile.
         */
        ExpressInterestRequest: {
            /**
             * View Id
             * Format: uuid
             */
            view_id: string;
        };
        /**
         * ExpressInterestResponse
         * @description Response when expressing interest.
         */
        ExpressInterestResponse: {
            /** Success */
            success: boolean;
            interest_type: components["schemas"]["InterestType"];
            /** View Duration Seconds */
            view_duration_seconds: number;
            next_profile?: components["schemas"]["DailyDiscoveryProfileOut"] | null;
            /**
             * Is Complete
             * @default false
             */
            is_complete: boolean;
            /** Error */
            error?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * InterestType
         * @enum {string}
         */
        InterestType: "free_pick" | "earned";
        /** LikeCreate */
        LikeCreate: {
            /**
             * To User Id
             * Format: uuid
             */
            to_user_id: string;
            /** Message */
            message?: string | null;
            /** Liked Item */
            liked_item?: string | null;
        };
        /** LikeResultOut */
        LikeResultOut: {
            /** Success */
            success: boolean;
            /** Is Match */
            is_match: boolean;
            /** Match Id */
            match_id: string | null;
            /** Error */
            error: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MatchOut */
        MatchOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Other User Id
             * Format: uuid
             */
            other_user_id: string;
            /** Other User Name */
            other_user_name: string | null;
            /** Other User Photo */
            other_user_photo: string | null;
            /**
             * Matched At
             * Format: date-time
             */
            matched_at: string;
            /** Status */
            status: string;
            /** Last Message At */
            last_message_at: string | null;
        };
        /** MessageCreate */
        MessageCreate: {
            /** Content */
            content: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /**
             * Sender Id
             * Format: uuid
             */
            sender_id: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Read At */
            read_at: string | null;
            /** Is Own */
            is_own: boolean;
        };
        /** MessagesResponse */
        MessagesResponse: {
            /** Messages */
            messages: components["schemas"]["MessageResponse"][];
            /** Has More */
            has_more: boolean;
        };
        /** PassCreate */
        PassCreate: {
            /**
             * To User Id
             * Format: uuid
             */
            to_user_id: string;
        };
        /** PassOut */
        PassOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * To User Id
             * Format: uuid
             */
            to_user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * PassProfileRequest
         * @description Request to pass on a profile.
         */
        PassProfileRequest: {
            /**
             * View Id
             * Format: uuid
             */
            view_id: string;
        };
        /**
         * PassProfileResponse
         * @description Response when passing on a profile.
         */
        PassProfileResponse: {
            /** Success */
            success: boolean;
            next_profile?: components["schemas"]["DailyDiscoveryProfileOut"] | null;
            /**
             * Is Complete
             * @default false
             */
            is_complete: boolean;
            /** Error */
            error?: string | null;
        };
        /** PendingLikeOut */
        PendingLikeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * From User Id
             * Format: uuid
             */
            from_user_id: string;
            /** From User Name */
            from_user_name: string | null;
            /** From User Photo */
            from_user_photo: string | null;
            /** Message */
            message: string | null;
            /** Liked Item */
            liked_item: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PhotoCreate */
        PhotoCreate: {
            /** Url */
            url: string;
            /**
             * Order
             * @default 0
             */
            order: number;
        };
        /** PhotoReorder */
        PhotoReorder: {
            /** Photo Ids */
            photo_ids: string[];
        };
        /** PhotoResponse */
        PhotoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Url */
            url: string;
            /** Order */
            order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProfileCompletion */
        ProfileCompletion: {
            /** Percentage */
            percentage: number;
            /** Has Photos */
            has_photos: boolean;
            /** Photo Count */
            photo_count: number;
            /** Has Prompts */
            has_prompts: boolean;
            /** Prompt Count */
            prompt_count: number;
            /** Has Quiz */
            has_quiz: boolean;
            /** Has Basic Info */
            has_basic_info: boolean;
            /** Missing */
            missing: string[];
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Name */
            name?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Gender */
            gender?: string | null;
            /** Bio */
            bio?: string | null;
            /** Location */
            location?: string | null;
            /** Looking For */
            looking_for?: string | null;
            /** Height Cm */
            height_cm?: number | null;
        };
        /** PromptCreate */
        PromptCreate: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
        };
        /** PromptResponse */
        PromptResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Order */
            order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PromptUpdate */
        PromptUpdate: {
            /** Answer */
            answer: string;
        };
        /** QuizAnswer */
        QuizAnswer: {
            /** Question Key */
            question_key: string;
            /** Answer Value */
            answer_value: number;
        };
        /** QuizResponseOut */
        QuizResponseOut: {
            /** Question Key */
            question_key: string;
            /** Answer Value */
            answer_value: number;
        };
        /** QuizSubmit */
        QuizSubmit: {
            /** Answers */
            answers: components["schemas"]["QuizAnswer"][];
        };
        /** ReportCreate */
        ReportCreate: {
            /**
             * Reported Id
             * Format: uuid
             */
            reported_id: string;
            reason: components["schemas"]["ReportReason"];
            /** Details */
            details?: string | null;
        };
        /** ReportOut */
        ReportOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Reported Id
             * Format: uuid
             */
            reported_id: string;
            /** Reason */
            reason: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReportReason
         * @enum {string}
         */
        ReportReason: "fake_profile" | "inappropriate_content" | "harassment" | "spam" | "underage" | "other";
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TokenRefresh */
        TokenRefresh: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** TraitComparisonOut */
        TraitComparisonOut: {
            /** Trait Name */
            trait_name: string;
            /** User Score */
            user_score: number;
            /** Other Score */
            other_score: number;
            /** Difference */
            difference: number;
            /** Compatibility */
            compatibility: string;
            /** Description */
            description: string;
        };
        /**
         * UnmatchReason
         * @enum {string}
         */
        UnmatchReason: "not_interested" | "no_response" | "inappropriate" | "met_offline" | "other";
        /** UnmatchRequest */
        UnmatchRequest: {
            reason: components["schemas"]["UnmatchReason"];
        };
        /** UnreadCountResponse */
        UnreadCountResponse: {
            /** Unread Count */
            unread_count: number;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string | null;
            /** Is Active */
            is_active: boolean;
            /** Birth Date */
            birth_date: string | null;
            /** Gender */
            gender: string | null;
            /** Bio */
            bio: string | null;
            /** Location */
            location: string | null;
            /** Looking For */
            looking_for: string | null;
            /** Height Cm */
            height_cm: number | null;
            /** Profile Complete */
            profile_complete: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ViewEndRequest
         * @description Request to end viewing (interest or pass).
         */
        ViewEndRequest: {
            /**
             * View Id
             * Format: uuid
             */
            view_id: string;
            /** Action */
            action: string;
        };
        /**
         * ViewEndResponse
         * @description Response when ending a view.
         */
        ViewEndResponse: {
            /** Success */
            success: boolean;
            /** View Duration Seconds */
            view_duration_seconds: number;
            /** Action */
            action: string;
            interest_type?: components["schemas"]["InterestType"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ViewStartRequest
         * @description Request to start viewing a profile.
         */
        ViewStartRequest: {
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
        };
        /**
         * ViewStartResponse
         * @description Response when starting to view a profile.
         */
        ViewStartResponse: {
            /**
             * View Id
             * Format: uuid
             */
            view_id: string;
            profile: components["schemas"]["DailyDiscoveryProfileOut"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Minimum View Seconds
             * @description Minimum seconds before interest allowed
             * @default 20
             */
            minimum_view_seconds: number;
            /**
             * Is Free Pick
             * @description Whether this is the user's free pick (no wait required)
             */
            is_free_pick: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    signup_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_current_user_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_photos_v1_profile_photos_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_photo_v1_profile_photos_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_photo_v1_profile_photos__photo_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                photo_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_user_photos_v1_profile_photos_reorder_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoReorder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_available_prompts_v1_profile_prompts_available_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailablePromptsResponse"];
                };
            };
        };
    };
    list_prompts_v1_profile_prompts_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_prompt_v1_profile_prompts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_prompt_v1_profile_prompts__prompt_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                prompt_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_prompt_v1_profile_prompts__prompt_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                prompt_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quiz_responses_v1_profile_quiz_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_quiz_answers_v1_profile_quiz_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadgeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_badges_v1_profile_badges_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadgeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_completion_v1_profile_completion_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileCompletion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_discovery_feed_v1_matching_discover_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_like_to_user_v1_matching_likes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LikeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_likes_received_v1_matching_likes_pending_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingLikeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pass_on_user_v1_matching_passes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PassCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_pass_on_user_v1_matching_passes__to_user_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                to_user_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_v1_matching_matches_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unmatch_user_v1_matching_matches__match_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                match_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnmatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    block_another_user_v1_matching_blocks_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_another_user_v1_matching_reports_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_compatibility_v1_matching_compatibility__other_user_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                other_user_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompatibilityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_discovery_v1_daily_discovery_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyDiscoveryInitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_view_v1_daily_discovery_view_start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_view_v1_daily_discovery_view_end_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewEndRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewEndResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    express_interest_v1_daily_discovery_interest_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpressInterestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpressInterestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pass_profile_v1_daily_discovery_pass_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PassProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_for_testing_v1_daily_discovery_reset_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_v1_chat_matches__match_id__messages_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                match_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_v1_chat_matches__match_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                match_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_v1_chat_matches__match_id__read_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                match_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_unread_count_v1_chat_matches__match_id__unread_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                match_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_message_v1_chat_messages__message_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                message_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
