from app.schemas.user import LoginRequest, ProfileUpdate, Token, TokenRefresh, UserCreate, UserResponse
from app.schemas.profile import (
    AVAILABLE_PROMPTS,
    AvailablePromptsResponse,
    BadgeResponse,
    PhotoCreate,
    PhotoReorder,
    PhotoResponse,
    ProfileCompletion,
    PromptCreate,
    PromptResponse,
    PromptUpdate,
    QuizAnswer,
    QuizResponseOut,
    QuizSubmit,
)
from app.schemas.matching import (
    BlockCreate,
    BlockOut,
    CompatibilityOut,
    DiscoveryProfileOut,
    DiscoveryResultOut,
    LikeCreate,
    LikeResultOut,
    MatchOut,
    PassCreate,
    PassOut,
    PendingLikeOut,
    ReportCreate,
    ReportOut,
    TraitComparisonOut,
    UnmatchRequest,
)

__all__ = [
    # User
    "UserCreate",
    "UserResponse",
    "ProfileUpdate",
    "Token",
    "TokenRefresh",
    "LoginRequest",
    # Profile
    "PhotoCreate",
    "PhotoResponse",
    "PhotoReorder",
    "PromptCreate",
    "PromptUpdate",
    "PromptResponse",
    "QuizAnswer",
    "QuizSubmit",
    "QuizResponseOut",
    "BadgeResponse",
    "ProfileCompletion",
    "AvailablePromptsResponse",
    "AVAILABLE_PROMPTS",
    # Matching
    "BlockCreate",
    "BlockOut",
    "CompatibilityOut",
    "DiscoveryProfileOut",
    "DiscoveryResultOut",
    "LikeCreate",
    "LikeResultOut",
    "MatchOut",
    "PassCreate",
    "PassOut",
    "PendingLikeOut",
    "ReportCreate",
    "ReportOut",
    "TraitComparisonOut",
    "UnmatchRequest",
]
